[pytest]
pythonpath = .
testpaths = tests
filterwarnings =
    # fiftyone uses a deprecated datetime method, causing many warnings
    ignore:datetime.datetime.utcnow() is deprecated:DeprecationWarning